version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test:
    executor: node/default
    working_directory: ~/Share-Space
    steps:
      - checkout
      - run:
          command: cd server && pwd
          name: Go to server
      - run:
          command: pwd && npm install
          name: install packages
      - run:
          command: npm test
          name: Run tests

workflows:
  test_my_app:
    jobs:
      - build_and_test
