version: 2.1
orbs:
  node: circleci/node@5.0.2

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - run:
          command: cd server
          name: Go to server
      - run:
          command: npm install
          name: install packages
      - run:
          command: npm test
          name: Run tests
      - persist_to_workspace:
          root: ~/project
          paths:
            - .

workflows:
  test_my_app:
    jobs:
      - build_and_test
